name: 'Version Updater'
description: 'Updates the version of a package metadata file'
inputs:
  git-email:
    description: 'Email used for git commits.'
    required: false
    default: 'action@github.com'
  git-username:
    description: 'Username used for git commits.'
    required: false
    default: 'GitHub Actions'
  target-version:
    description: 'The version to update to.'
    required: true
  target-file:
    description: 'The file to update.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
