name: Action test

on:
  push:
    branches:
      - dev

jobs:

  version-update:

    runs-on: ubuntu-latest
    name: Version update

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Generate random reference tag
        id: generate-tag
        run: echo ::set-output name=tag::$(echo $RANDOM)
        env:
          RANDOM: ${{ github.run_id }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Version updater action
        uses: ./
        with:
          git-email: "test@example.com"
          git-username: "Test User"
          target-version: "1.0.${{ steps.generate-tag.outputs.tag }}"
          target-file: ".github/sample.json"
          target-branch: "dev"
